### ISSUE TITLE
Setting up the Repository

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/react-calculator-app#1]
## 💰 Motivation
We are creating a repository for this project and are going to need to set up and adjust the directory.

## 📐 Plan
Add frameworks, directories, libraries, and files for our repository.

## ✅ Task List
- [x] Create and modify a linter file to easily find errors in code.
- [x] Create a .gitignore file to better suite our project.
- [x] Create a package.json file and input frameworks and libraries for our project.
- [x] Create directories for files in the app
- [x] Create an HTML Skeleton
- [x] Create a styles.css file and add border-box values
